apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: {{ .Release.Namespace }}
spec:
  instances: {{ .Values.postgres.replicas }}
  bootstrap:
    initdb:
      database: app
      owner: {{ .Values.postgres.username }}
      secret: 
        name: postgres-auth-secret
  storage:
    size: {{ .Values.postgres.size }}
    {{- with .Values.postgres.storageClass }}
    storageClass: {{ . }}
    {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-auth-secret
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.postgres.username }}
  password: {{ .Values.postgres.password }}