apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.rabbitmq.replicas }}
  persistence:
    storage: {{ .Values.rabbitmq.size }}
    {{- with .Values.rabbitmq.storageClass }}
    storageClassName: {{ . }}
    {{- end }}
